package com.example.shopsphere.CleanArchitecture.ui.models

import java.util.UUID

/**
 * Sealed hierarchy for chat messages rendered in the Sphere AI screen.
 * Each subtype maps to a different RecyclerView view type.
 */
sealed class ChatMessage {
    abstract val id: String
    abstract val timestamp: Long

    data class UserMessage(
        override val id: String = UUID.randomUUID().toString(),
        override val timestamp: Long = System.currentTimeMillis(),
        val text: String
    ) : ChatMessage()

    data class BotMessage(
        override val id: String = UUID.randomUUID().toString(),
        override val timestamp: Long = System.currentTimeMillis(),
        val text: String,
        val isError: Boolean = false,
        // Quick deep-link actions surfaced under the bubble (e.g. "View order
        // #1234", "Open product"). Generated by the use case after Gemini
        // replies, by cross-referencing mentioned order numbers / product
        // titles against the data the model was given.
        val actions: List<ChatAction> = emptyList()
    ) : ChatMessage()

    data class TypingIndicator(
        override val id: String = "typing_indicator",
        override val timestamp: Long = System.currentTimeMillis()
    ) : ChatMessage()
}

/**
 * A tappable shortcut attached to a bot reply. Each variant maps to a
 * navigation destination — the fragment owns the routing.
 */
sealed class ChatAction {
    abstract val label: String

    data class ViewOrder(
        val orderId: String,
        override val label: String
    ) : ChatAction()

    data class OpenProduct(
        val productId: Int,
        override val label: String
    ) : ChatAction()
}
