name: ShopSphere
options:
  bundleIdPrefix: com.shopsphere
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  FirebaseSDK:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: "11.0.0"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    majorVersion: "7.0.0"
  FacebookSDK:
    url: https://github.com/facebook/facebook-ios-sdk
    majorVersion: "17.0.0"
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    majorVersion: "4.0.0"
  Stripe:
    url: https://github.com/stripe/stripe-ios
    majorVersion: "23.0.0"

targets:
  ShopSphere:
    type: application
    platform: iOS
    sources:
      - ShopSphere
    settings:
      base:
        INFOPLIST_FILE: ShopSphere/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.shopsphere.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: "V9KZBKD7F9"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
    dependencies:
      - package: FirebaseSDK
        product: FirebaseAuth
      - package: FirebaseSDK
        product: FirebaseFirestore
      - package: FirebaseSDK
        product: FirebaseAnalytics
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: FacebookSDK
        product: FacebookLogin
      - package: FacebookSDK
        product: FacebookCore
      - package: Lottie
        product: Lottie
      - package: Stripe
        product: StripePaymentSheet
